package trabalho_completo.model.enums;

public enum OpcoesMenuEnum {
    CIRCULO, QUADRADO, RETANGULO, LOSANGO, TRAPEZIO, TRIANGULO, PONTO, RETA, TEXTO, LISTAR, APAGAR, DESENHAR, SAIR, FAIL,
    SALVAR, RECUPERAR, BACKUP,
    NOVO, EDITAR, MOSTRAR, EXCLUIR, VOLTAR,RESETAR
}